[package]
name = "charabyx_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "charabyx_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
charabia = "0.6.0"